{
 "title": "System Health Overview",
 "tags": [
  "system",
  "infrastructure"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "service",
    "label": "Spring Boot Service",
    "query": {
     "query": "label_values(jvm_memory_used_bytes, job)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Nginx Ingress Health",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "NGINX Status for $instance",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 12, "x": 0, "y": 1 },
     "repeat": "instance",
     "format": "none",
     "valueName": "current",
     "targets": [
      { "expr": "nginx_up" }
     ]
    },
    {
     "title": "Processed connections",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "short", "label": "Connections (rate)" }
     ],
     "targets": [
      {
       "expr": "irate(nginx_connections_accepted[5m])",
       "legendFormat": "{{instance}} accepted"
      },
      {
       "expr": "irate(nginx_connections_handled[5m])",
       "legendFormat": "{{instance}} handled"
      }
     ]
    },
    {
     "title": "Active Connections",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 5 },
     "yaxes": [
      { "format": "short", "label": "Connections" }
     ],
     "targets": [
      { "expr": "nginx_connections_active", "legendFormat": "{{instance}} active" },
      { "expr": "nginx_connections_reading", "legendFormat": "{{instance}} reading" },
      { "expr": "nginx_connections_waiting", "legendFormat": "{{instance}} waiting" },
      { "expr": "nginx_connections_writing", "legendFormat": "{{instance}} writing" }
     ]
    },
    {
     "title": "Total requests",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "irate(nginx_http_requests_total[5m])",
       "legendFormat": "{{instance}} total requests"
      }
     ]
    }
   ]
  },
  {
   "title": "FastAPI Service Health",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Requests",
     "type": "stat",
     "gridPos": { "h": 12, "w": 4, "x": 0, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(http_requests_total{job=\"genai-service\", handler!=\"/metrics\"})"
      }
     ]
    },
    {
     "title": "Requests Count",
     "type": "stat",
     "gridPos": { "h": 12, "w": 7, "x": 4, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "http_requests_total{job=\"genai-service\", handler!=\"/metrics\"}",
       "legendFormat": "{{method}} {{handler}}"
      }
     ]
    },
    {
     "title": "Requests Average Duration",
     "type": "bargauge",
     "gridPos": { "h": 12, "w": 13, "x": 11, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "http_request_duration_seconds_sum{job=\"genai-service\"} / http_request_duration_seconds_count{job=\"genai-service\"}",
       "legendFormat": "{{method}} {{handler}}"
      }
     ]
    },
    {
     "title": "Percent of 2xx Requests",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 11, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum by(handler) (http_requests_total{job=\"genai-service\", status=~\"2.*\", handler!=\"/metrics\"}) / sum by(handler) (http_requests_total{job=\"genai-service\", handler!=\"/metrics\"})",
       "legendFormat": "{{handler}}"
      }
     ]
    },
    {
     "title": "Percent of 5xx Requests",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 13, "x": 11, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum by(handler) (http_requests_total{job=\"genai-service\", status=~\"5.*\", handler!=\"/metrics\"}) / sum by(handler) (http_requests_total{job=\"genai-service\", handler!=\"/metrics\"})",
       "legendFormat": "{{handler}}"
      }
     ]
    },
    {
     "title": "PR 99 Requests Duration",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(.99,sum(rate(http_request_duration_seconds_bucket{job=\"genai-service\", handler!=\"/metrics\"}[1m])) by(path, le))",
       "legendFormat": "{{path}}"
      }
     ]
    },
    {
     "title": "Request time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 21 },
     "targets": [
      {
       "expr": "http_request_duration_seconds_sum{job=\"genai-service\"} / http_request_duration_seconds_count{job=\"genai-service\"}",
       "legendFormat": "{{handler}}"
      }
     ]
    },
    {
     "title": "Request Per Sec",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "rate(http_requests_total{job=\"genai-service\"}[1m])",
       "legendFormat": "{{handler}}"
      }
     ]
    },
    {
     "title": "Python Process Resident Memory Use",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "process_resident_memory_bytes{job=\"genai-service\"}",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Python Process CPU Use",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "irate(process_cpu_seconds_total{job=\"genai-service\"}[5m])*10",
       "legendFormat": "{{job}}"
      }
     ]
    }
   ]
  },
  {
   "title": "JVM & Spring Boot Service Health",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Uptime",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 8, "x": 0, "y": 0 },
     "format": "s",
     "valueName": "current",
     "targets": [
      {
       "expr": "process_uptime_seconds{job=\"$service\"}"
      }
     ]
    },
    {
     "title": "Heap used",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 8, "x": 8, "y": 0 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(jvm_memory_used_bytes{job=\"$service\", area=\"heap\"})*100/sum(jvm_memory_max_bytes{job=\"$service\", area=\"heap\"})"
      }
     ]
    },
    {
     "title": "Non-Heap used",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 8, "x": 16, "y": 0 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(jvm_memory_used_bytes{job=\"$service\", area=\"nonheap\"})*100/sum(jvm_memory_max_bytes{job=\"$service\", area=\"nonheap\"})"
      }
     ]
    },
    {
     "title": "Rate",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(rate(http_server_requests_seconds_count{job=\"$service\"}[1m]))",
       "legendFormat": "HTTP"
      }
     ]
    },
    {
     "title": "Errors",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 4 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(rate(http_server_requests_seconds_count{job=\"$service\", status=~\"5..\"}[1m]))",
       "legendFormat": "HTTP - 5xx"
      }
     ]
    },
    {
     "title": "Duration",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 4 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum(rate(http_server_requests_seconds_sum{job=\"$service\", status!~\"5..\"}[1m]))/sum(rate(http_server_requests_seconds_count{job=\"$service\", status!~\"5..\"}[1m]))",
       "legendFormat": "HTTP - AVG"
      },
      {
       "expr": "max(http_server_requests_seconds_max{job=\"$service\", status!~\"5..\"})",
       "legendFormat": "HTTP - MAX"
      }
     ]
    },
    {
     "title": "CPU Usage",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "system_cpu_usage{job=\"$service\"}",
       "legendFormat": "system"
      },
      {
       "expr": "process_cpu_usage{job=\"$service\"}",
       "legendFormat": "process"
      },
      {
       "expr": "avg_over_time(process_cpu_usage{job=\"$service\"}[15m])",
       "legendFormat": "process-15m"
      }
     ]
    },
    {
     "title": "JVM Heap",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 10 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(jvm_memory_used_bytes{job=\"$service\", area=\"heap\"})",
       "legendFormat": "used"
      },
      {
       "expr": "sum(jvm_memory_committed_bytes{job=\"$service\", area=\"heap\"})",
       "legendFormat": "committed"
      },
      {
       "expr": "sum(jvm_memory_max_bytes{job=\"$service\", area=\"heap\"})",
       "legendFormat": "max"
      }
     ]
    },
    {
     "title": "JVM Non-Heap",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 10 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(jvm_memory_used_bytes{job=\"$service\", area=\"nonheap\"})",
       "legendFormat": "used"
      },
      {
       "expr": "sum(jvm_memory_committed_bytes{job=\"$service\", area=\"nonheap\"})",
       "legendFormat": "committed"
      },
      {
       "expr": "sum(jvm_memory_max_bytes{job=\"$service\", area=\"nonheap\"})",
       "legendFormat": "max"
      }
     ]
    },
    {
     "title": "GC Pressure",
     "type": "graph",
     "description": "The percent of time spent on Garbage Collection over all CPUs assigned to the JVM process.",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(rate(jvm_gc_pause_seconds_sum{job=\"$service\"}[1m])) by (application, instance) / on(application, instance) system_cpu_count",
       "legendFormat": "CPU time spent on GC"
      }
     ]
    },
    {
     "title": "Collections",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 16 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "rate(jvm_gc_pause_seconds_count{job=\"$service\"}[1m])",
       "legendFormat": "{{action}} ({{cause}})"
      }
     ]
    },
    {
     "title": "Pause Durations",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 16 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "rate(jvm_gc_pause_seconds_sum{job=\"$service\"}[1m])/rate(jvm_gc_pause_seconds_count{job=\"$service\"}[1m])",
       "legendFormat": "avg {{action}} ({{cause}})"
      },
      {
       "expr": "jvm_gc_pause_seconds_max{job=\"$service\"}",
       "legendFormat": "max {{action}} ({{cause}})"
      }
     ]
    },
    {
     "title": "Threads",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jvm_threads_live_threads{job=\"$service\"}",
       "legendFormat": "live"
      },
      {
       "expr": "jvm_threads_daemon_threads{job=\"$service\"}",
       "legendFormat": "daemon"
      },
      {
       "expr": "jvm_threads_peak_threads{job=\"$service\"}",
       "legendFormat": "peak"
      },
      {
       "expr": "process_threads{job=\"$service\"}",
       "legendFormat": "process"
      }
     ]
    },
    {
     "title": "File Descriptors",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 22 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "process_files_open_files{job=\"$service\"}",
       "legendFormat": "open"
      },
      {
       "expr": "process_files_max_files{job=\"$service\"}",
       "legendFormat": "max"
      }
     ]
    },
    {
     "title": "Classes loaded",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 22 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jvm_classes_loaded_classes{job=\"$service\"}",
       "legendFormat": "loaded"
      }
     ]
    }
   ]
  }
 ]
}