{{- if .Values.prometheus.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-deployment
  labels:
    {{- include "open-thesis-radar.componentLabels" (dict "root" . "name" "prometheus" "component" "monitoring") | nindent 4 }}
spec:
  replicas: {{ .Values.prometheus.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: prometheus
      app.kubernetes.io/instance: {{ .Release.Name | quote }}
  template:
    metadata:
      labels:
        {{- include "open-thesis-radar.componentLabels" (dict "root" . "name" "prometheus" "component" "monitoring") | nindent 8 }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/prometheus-configmap.yaml") . | sha256sum }}
    spec:
      containers:
        - name: prometheus-container
          image: "{{ .Values.prometheus.image.repository }}:{{ .Values.prometheus.image.tag }}"
          ports:
            - containerPort: 9090
              name: http
          resources:
            {{- toYaml .Values.prometheus.resources | nindent 12 }}
          volumeMounts:
            - name: config-volume
              mountPath: /etc/prometheus
            - name: storage-volume
              mountPath: /prometheus
      volumes:
        - name: config-volume
          configMap:
            name: prometheus-config
        - name: storage-volume
          {{- if .Values.prometheus.persistence.enabled }}
          persistentVolumeClaim:
            claimName: prometheus-pvc
          {{- else }}
          emptyDir: {}
          {{- end }}
{{- end }}
