server:
  port: 8081

spring:
  application:
    name: scraping-service

app:
  client:
    main-thesis:
      url: ${APP_SERVICES_MAIN_THESIS:http://localhost:8080}
    genai:
      url: ${APP_SERVICES_GENAI:http://localhost:8000}
    timeouts:
      connect-ms: ${CLIENT_CONNECT_TIMEOUT:4000}
      read-ms: ${CLIENT_READ_TIMEOUT:120000}
  scheduling:
    #Every Monday at 03:30
    scrape-cron: "0 30 3 * * MON"

# Actuator config for DevOps health checks
management:
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      base-path: /
      exposure:
        include: health, info
