apiVersion: v1
kind: Service
metadata:
  name: scraping-service
  namespace: open-thesis-radar
  labels:
    app: scraping-service
spec:
  selector:
    app: scraping-service
  ports:
    - protocol: TCP
      port: 8081
      targetPort: scraping-service-port
