---
apiVersion: v1
kind: Secret
metadata:
  name: thesis-db-secret
  namespace: open-thesis-radar
type: Opaque
stringData:
  # username must match auth.username in helm-values/thesis-db-values.yml (thesis_user)
  username: thesis_user
  password: CHANGE_ME

---
apiVersion: v1
kind: Secret
metadata:
  name: vector-db-secret
  namespace: open-thesis-radar
type: Opaque
stringData:
  # username must match auth.username in helm-values/vector-db-values.yml (vector_user)
  username: vector_user
  password: CHANGE_ME

---
apiVersion: v1
kind: Secret
metadata:
  name: azure-openai-secret
  namespace: open-thesis-radar
type: Opaque
stringData:
  endpoint: CHANGE_ME
  api-key: CHANGE_ME

---
apiVersion: v1
kind: Secret
metadata:
  name: openai-secret
  namespace: open-thesis-radar
type: Opaque
stringData:
  api-key: CHANGE_ME
