server:
  port: 8081

spring:
  application:
    name: ingestion-service

app:
  services:
    main-thesis: http://localhost:8080
    genai: http://localhost:8000
  scheduling:
    scrape-cron: "0 0 * * * *"

# Actuator config for DevOps health checks
management:
  endpoints:
    web:
      base-path: /
      exposure:
        include: health, info
