{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: open-thesis-radar
  labels:
{{- include "open-thesis-radar.componentLabels" (dict "root" . "name" "open-thesis-radar" "component" "ingress") | nindent 4 }}
  annotations:
{{- toYaml .Values.ingress.annotations | nindent 4 }}
spec:
  {{- if .Values.ingress.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.ingress.host | quote }}
      secretName: {{ .Values.ingress.tls.secretName }}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.host | quote }}
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: thesis-service
                port:
                  number: 8080
          - path: /
            pathType: Prefix
            backend:
              service:
                name: user-interface
                port:
                  number: 80
{{- end }}
