/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/theses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List all theses
         * @description Fetch all thesis proposals currently stored in the database.
         */
        get: operations["listTheses"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/theses/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Search and filter theses
         * @description Search thesis proposals using traditional filters, natural language, or both.
         *
         *     Request examples:
         *     - Only filters: `degreeType = "MASTER"`, `researchAreas = ["AI"]`
         *     - Only natural language: `"I want a thesis about semantic search with LLMs"`
         *     - Hybrid: natural language query plus traditional filters
         *
         *     The Thesis Service fetches matching structured data from PostgreSQL.
         *     If `naturalLanguageQuery` is present, it also calls the Vector Search Service
         *     and combines vector results with relational filtering.
         */
        post: operations["searchTheses"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/theses/{thesisId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get thesis details
         * @description Fetch one thesis proposal by id.
         */
        get: operations["getThesisById"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/chairs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List chairs
         * @description Fetch chairs for frontend filters.
         */
        get: operations["listChairs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/filters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get available filter values
         * @description Fetch available filter values such as degree types, research areas, and chairs.
         */
        get: operations["getAvailableFilters"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/v1/thesis-service/source-endpoints": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List source endpoints for scraping
         * @description Called by the Scraping Service before a scrape cycle.
         *
         *     The Thesis Service returns all configured chair websites/source endpoints that should be scraped.
         *     The Scraping Service then processes them sequentially.
         */
        get: operations["listSourceEndpointsForScraping"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/v1/thesis-service/research-areas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List known research areas for extraction
         * @description Returns canonical/known research area names that the GenAI service should prefer during extraction.
         */
        get: operations["listKnownResearchAreasForScraping"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/v1/thesis-service/scrape-runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Log a scrape run result
         * @description Called by the Scraping Service to record the outcome of a scrape attempt.
         *     This should be called for both successful and failed runs to maintain a complete history.
         */
        post: operations["logScrapeRun"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/v1/thesis-service/source-endpoints/{sourceEndpointId}/theses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Replace all thesis proposals for a chair
         * @description Called by the Scraping Service only after successful scraping and successful
         *     GenAI extraction for one chair/source endpoint.
         *
         *     Thesis Service behavior:
         *     1. In one transaction, delete all existing thesis proposals for `chairId`
         *        and insert the newly extracted thesis proposals.
         *     2. Commit only if the full replacement succeeds.
         *     3. After relational replacement succeeds, call the Vector Search Service
         *        to replace the vector index entries for the same chair.
         *
         *     If validation or insertion fails, the old thesis data must remain unchanged.
         */
        put: operations["replaceChairTheses"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/thesis-internal/v1/source-endpoints/{sourceEndpointId}/detect-changes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Detect if source endpoint content has changed
         * @description Called by the Scraping Service before calling the GenAI Service.
         *     The Thesis Service normalizes the HTML, hashes it, and checks if it matches the stored hash.
         */
        post: operations["detectChanges"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/v1/scraping-service/scrape": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Trigger a scrape run
         * @description Starts a scrape run in the Scraping Service for all source endpoints returned by the Thesis Service.
         *     This endpoint can be used by a scheduled job or manually for demo/testing.
         */
        post: operations["triggerScrape"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/v1/vector-search-service/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Semantic thesis search
         * @description Called by the Thesis Service when the frontend sends a natural language query.
         *
         *     The Vector Search Service embeds the query, searches the vector database, and returns matching thesis ids
         *     with similarity scores. The Thesis Service can then fetch full thesis data from PostgreSQL and apply
         *     additional traditional filters.
         */
        post: operations["semanticSearch"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/v1/vector-search-service/source-endpoints/{sourceEndpointId}/index": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Replace vector index entries for a chair
         * @description Called by the Thesis Service after relational thesis replacement succeeded.
         *
         *     Vector Search Service behavior:
         *     1. Delete all existing vector index entries belonging to `chairId`.
         *     2. Generate embeddings for the provided theses.
         *     3. Insert the new vector index entries.
         */
        post: operations["indexSourceEndpointTheses"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/v1/genai-service/extract-theses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Extract structured theses from scraped content
         * @description Called by the Scraping Service after it downloads raw HTML/text from a source endpoint.
         *
         *     The GenAI Service returns structured thesis proposals extracted from the raw content.
         *     It does not write to PostgreSQL or the vector database.
         */
        post: operations["extractThesesFromRawContent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health check
         * @description Generic health endpoint implemented by every service.
         */
        get: operations["healthCheck"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        SearchThesesRequest: {
            /**
             * @description Optional natural language query used for semantic search.
             * @example I want a thesis about semantic search with LLMs
             */
            naturalLanguageQuery?: string | null;
            filters?: components["schemas"]["ThesisSearchFilters"];
            /** @default 0 */
            page: number;
            /** @default 20 */
            size: number;
        };
        ThesisSearchFilters: {
            chairIds?: number[];
            degreeTypes?: string[];
            researchAreas?: string[];
            /** @example OPEN */
            status?: string | null;
        };
        SearchThesesResponse: {
            items: components["schemas"]["ThesisSearchResult"][];
            /** @example 0 */
            page: number;
            /** @example 20 */
            size: number;
            /** @example 123 */
            totalElements: number;
        };
        ThesisSearchResult: components["schemas"]["ThesisProposal"] & {
            /**
             * Format: float
             * @description Present when result came from semantic/vector search.
             * @example 0.87
             */
            semanticScore?: number | null;
        };
        Chair: {
            /**
             * Format: int64
             * @example 3
             */
            id: number;
            /** @example Chair of Software Engineering */
            name: string;
            /**
             * Format: uri
             * @example https://example-chair.tum.de
             */
            websiteUrl: string;
        };
        SourceEndpoint: {
            /**
             * Format: int64
             * @example 10
             */
            id: number;
            /**
             * Format: int64
             * @example 3
             */
            chairId: number;
            /** @example Chair of Software Engineering */
            chairName?: string;
            /**
             * Format: uri
             * @example https://example-chair.tum.de/theses
             */
            url: string;
            /** @example ACTIVE */
            status: string;
            /** Format: date-time */
            lastScrapedAt?: string | null;
            /** @example e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855 */
            lastContentHash?: string | null;
        };
        SourceEndpointListResponse: {
            endpoints: components["schemas"]["SourceEndpoint"][];
        };
        ThesisProposal: {
            /**
             * Format: int64
             * @example 1001
             */
            id: number;
            /**
             * Format: int64
             * @example 3
             */
            chairId: number;
            /** @example Chair of Software Engineering */
            chairName?: string | null;
            /** @example Semantic Search for Thesis Discovery */
            title: string;
            /** @example MASTER */
            degreeType?: string | null;
            originalDescription?: string | null;
            aiOverview?: string | null;
            /** @example Artificial Intelligence */
            researchArea?: string | null;
            /** Format: uri */
            sourceUrl: string;
            /** @example OPEN */
            status: string;
            /** Format: date-time */
            lastSeenAt?: string | null;
            advisors?: components["schemas"]["Advisor"][];
        };
        ThesisProposalInput: {
            title: string;
            degreeType?: string | null;
            originalDescription?: string | null;
            aiOverview?: string | null;
            researchArea?: string | null;
            /** Format: uri */
            sourceUrl: string;
            /** @default OPEN */
            status: string;
            advisors?: components["schemas"]["AdvisorInput"][];
        };
        Advisor: {
            /** Format: int64 */
            id?: number | null;
            name: string;
            /** Format: email */
            email: string;
            /** Format: uri */
            profileUrl?: string | null;
        };
        AdvisorInput: {
            name: string;
            /** Format: email */
            email?: string | null;
            /** Format: uri */
            profileUrl?: string | null;
        };
        ScrapeRunLogRequest: {
            /** Format: int64 */
            sourceEndpointId: number;
            /** Format: date-time */
            startedAt: string;
            /** Format: date-time */
            finishedAt: string;
            /** @enum {string} */
            status: "SUCCESS" | "PARTIAL_SUCCESS" | "FAILED";
            errorMessage?: string | null;
            /** @description Raw HTML snapshot of the source page, stored for debugging. */
            rawHtmlSnapshot?: string | null;
            /** @example 5 */
            candidatesFound?: number | null;
        };
        ScrapeRunLogResponse: {
            /** Format: int64 */
            id: number;
            status: string;
        };
        SourceEndpointThesesReplacementRequest: {
            theses: components["schemas"]["ThesisProposalInput"][];
            /** @example e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855 */
            lastContentHash?: string | null;
        };
        SourceEndpointThesesReplacementResponse: {
            /**
             * Format: int64
             * @example 10
             */
            sourceEndpointId: number;
            /** @example 12 */
            deletedRelationalTheses: number;
            /** @example 9 */
            insertedRelationalTheses: number;
            /** @example 9 */
            replacedVectorEntries: number;
            /** @example Vector search sync failed: connection refused */
            errorMessage?: string | null;
        };
        TriggerScrapeResponse: {
            /** @example true */
            started: boolean;
            /** @example Scrape run started. */
            message?: string;
        };
        KnownResearchAreasResponse: {
            researchAreas: string[];
        };
        GenAIExtractionRequest: {
            /** Format: int64 */
            sourceEndpointId: number;
            /** Format: int64 */
            chairId: number;
            chairName?: string | null;
            /** Format: uri */
            sourceUrl: string;
            rawHtml: string;
            /** @description Optional plain text extracted by the Scraping Service before calling GenAI. */
            extractedPlainText?: string | null;
            /** @description Existing/canonical research area names the model should reuse whenever possible. */
            knownResearchAreas?: string[];
        };
        GenAIExtractionResponse: {
            theses: components["schemas"]["ThesisProposalInput"][];
            extractionNotes?: string | null;
        };
        VectorSearchRequest: {
            query: string;
            filters?: components["schemas"]["VectorSearchFilters"];
            /** @default 50 */
            limit: number;
        };
        VectorSearchFilters: {
            chairIds?: number[];
            degreeTypes?: string[];
            researchAreas?: string[];
            status?: string | null;
        };
        VectorSearchResponse: {
            results: components["schemas"]["VectorSearchResult"][];
        };
        VectorSearchResult: {
            /**
             * Format: int64
             * @example 1001
             */
            thesisId: number;
            /**
             * Format: int64
             * @example 3
             */
            chairId?: number;
            /**
             * Format: float
             * @example 0.87
             */
            score: number;
        };
        ReplaceSourceEndpointVectorsRequest: {
            /** Format: int64 */
            scrapeRunId?: number | null;
            theses: components["schemas"]["VectorThesisDocument"][];
        };
        VectorThesisDocument: {
            /** Format: int64 */
            thesisId: number;
            /** Format: int64 */
            chairId: number;
            /** Format: int64 */
            sourceEndpointId: number;
            title: string;
            degreeType?: string | null;
            aiOverview?: string | null;
            originalDescription?: string | null;
            researchArea?: string | null;
            /** Format: uri */
            sourceUrl: string;
        };
        ReplaceSourceEndpointVectorsResponse: {
            /** Format: int64 */
            sourceEndpointId: number;
            /** @example 12 */
            deletedVectorEntries: number;
            /** @example 9 */
            insertedVectorEntries: number;
        };
        AvailableFiltersResponse: {
            chairs?: components["schemas"]["Chair"][];
            degreeTypes?: string[];
            researchAreas?: string[];
        };
        HealthResponse: {
            /** @example UP */
            status: string;
            /** @example main-thesis-service */
            service?: string | null;
        };
        ErrorResponse: {
            message: string;
            details?: {
                [key: string]: unknown;
            } | null;
        };
        DetectChangesRequest: {
            /** @description Raw HTML of the scraped page to be normalized and checked. */
            rawHtml: string;
        };
        DetectChangesResponse: {
            /** @description True if the normalized content hash differs from the last successfully processed hash. */
            changed: boolean;
            /** @description Cleaned semantic HTML that is safe and optimized for sending to GenAI. */
            sanitizedHtml?: string | null;
            /** @description The SHA-256 hash of the normalized text content. */
            contentHash: string;
        };
    };
    responses: never;
    parameters: {
        /** @description Internal source endpoint id. */
        SourceEndpointId: number;
        /** @description Internal chair id. */
        ChairId: number;
        /** @description Internal thesis proposal id. */
        ThesisId: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listTheses: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Thesis proposals returned successfully. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ThesisSearchResult"][];
                };
            };
        };
    };
    searchTheses: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SearchThesesRequest"];
            };
        };
        responses: {
            /** @description Search results returned successfully. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchThesesResponse"];
                };
            };
        };
    };
    getThesisById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Internal thesis proposal id. */
                thesisId: components["parameters"]["ThesisId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Thesis proposal found. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ThesisProposal"];
                };
            };
            /** @description Thesis proposal not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    listChairs: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Chairs returned successfully. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Chair"][];
                };
            };
        };
    };
    getAvailableFilters: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Available filters returned successfully. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AvailableFiltersResponse"];
                };
            };
        };
    };
    listSourceEndpointsForScraping: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Source endpoints returned successfully. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceEndpointListResponse"];
                };
            };
        };
    };
    listKnownResearchAreasForScraping: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Known research areas returned successfully. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KnownResearchAreasResponse"];
                };
            };
        };
    };
    logScrapeRun: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScrapeRunLogRequest"];
            };
        };
        responses: {
            /** @description Scrape run logged successfully. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScrapeRunLogResponse"];
                };
            };
        };
    };
    replaceChairTheses: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Internal source endpoint id. */
                sourceEndpointId: components["parameters"]["SourceEndpointId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "theses": [
                 *         {
                 *           "title": "Semantic Search for Thesis Discovery",
                 *           "degreeType": "MASTER",
                 *           "originalDescription": "This thesis investigates semantic search for university thesis proposals...",
                 *           "aiOverview": "Build and evaluate a semantic search pipeline for thesis discovery.",
                 *           "researchArea": "Artificial Intelligence",
                 *           "sourceUrl": "https://example-chair.tum.de/theses/semantic-search",
                 *           "status": "OPEN",
                 *           "advisors": [
                 *             {
                 *               "name": "Max Mustermann",
                 *               "email": "max.mustermann@example.com",
                 *               "profileUrl": "https://example-chair.tum.de/team/max"
                 *             }
                 *           ]
                 *         }
                 *       ]
                 *     }
                 */
                "application/json": components["schemas"]["SourceEndpointThesesReplacementRequest"];
            };
        };
        responses: {
            /** @description Chair thesis data replaced successfully. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceEndpointThesesReplacementResponse"];
                };
            };
            /** @description Invalid replacement payload. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    detectChanges: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Internal source endpoint id. */
                sourceEndpointId: components["parameters"]["SourceEndpointId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DetectChangesRequest"];
            };
        };
        responses: {
            /** @description Change status computed successfully. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DetectChangesResponse"];
                };
            };
            /** @description Source endpoint not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    triggerScrape: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Scrape run accepted. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TriggerScrapeResponse"];
                };
            };
        };
    };
    semanticSearch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "query": "I want a thesis about semantic search with LLMs",
                 *       "filters": {
                 *         "chairIds": [
                 *           3
                 *         ],
                 *         "degreeTypes": [
                 *           "MASTER"
                 *         ]
                 *       },
                 *       "limit": 50
                 *     }
                 */
                "application/json": components["schemas"]["VectorSearchRequest"];
            };
        };
        responses: {
            /** @description Vector search results returned successfully. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VectorSearchResponse"];
                };
            };
        };
    };
    indexSourceEndpointTheses: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Internal source endpoint id. */
                sourceEndpointId: components["parameters"]["SourceEndpointId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "scrapeRunId": 42,
                 *       "theses": [
                 *         {
                 *           "thesisId": 1001,
                 *           "chairId": 3,
                 *           "title": "Semantic Search for Thesis Discovery",
                 *           "degreeType": "MASTER",
                 *           "aiOverview": "Build and evaluate a semantic search pipeline for thesis discovery.",
                 *           "originalDescription": "This thesis investigates semantic search for university thesis proposals...",
                 *           "researchArea": "Artificial Intelligence",
                 *           "sourceUrl": "https://example-chair.tum.de/theses/semantic-search"
                 *         }
                 *       ]
                 *     }
                 */
                "application/json": components["schemas"]["ReplaceSourceEndpointVectorsRequest"];
            };
        };
        responses: {
            /** @description Vector index entries for the chair were replaced successfully. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReplaceSourceEndpointVectorsResponse"];
                };
            };
        };
    };
    extractThesesFromRawContent: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "sourceEndpointId": 10,
                 *       "chairId": 3,
                 *       "chairName": "Chair of Software Engineering",
                 *       "sourceUrl": "https://example-chair.tum.de/theses",
                 *       "rawHtml": "<html>...</html>",
                 *       "knownResearchAreas": [
                 *         "Artificial Intelligence",
                 *         "Robotics",
                 *         "Security"
                 *       ]
                 *     }
                 */
                "application/json": components["schemas"]["GenAIExtractionRequest"];
            };
        };
        responses: {
            /** @description Structured thesis proposals extracted successfully. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenAIExtractionResponse"];
                };
            };
            /** @description Extraction could not produce reliable structured output. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    healthCheck: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service is healthy. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
}
