FROM node:22-alpine AS build

WORKDIR /app

COPY package*.json ./
RUN npm ci

# COPY . .
COPY index.html .
COPY eslint.config.js .
COPY vite.config.ts .
COPY tsconfig.node.json .
COPY tsconfig.app.json .
COPY tsconfig.json .
COPY public ./public
COPY src ./src
RUN npm run build


FROM nginx:alpine

COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
